---
language: python
dist: xenial

python:
  - "3.5"

before_install:
  - mv travis_secrets.yaml secrets.yaml
  - pip install python-gilt
  - gilt overlay
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
...
