---
language: python
dist: xenial

python:
  - "3.5"

before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mkdir custom_components
  - wget https://raw.githubusercontent.com/custom-components/custom_updater/master/custom_components/custom_updater.py -O custom_components/custom_updater.py
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
...
