homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include customize.yaml

introduction:
frontend:
config:
http:
  api_password: !secret http_password
discovery:
history:
logbook:
sun:
sensor:
  - platform: yr

automation: !include includes/automations.yaml
device_tracker: !include includes/device_trackers.yaml
fan: !include includes/fans.yaml
media_player: !include includes/media_players.yaml
script: !include includes/scripts.yaml
shell_command: !include includes/shell_commands.yaml
switch: !include includes/switches.yaml
light: !include includes/lights.yaml
hue: !include includes/hue.yaml
homekit: !include includes/homekit.yaml
