---
- alias: PC shutdown
  trigger:
    - platform: state
      entity_id: device_tracker.pc
      from: 'home'
      to: 'not_home'
  action:
    - service: light.turn_off
      data:
        entity_id: light.bureau
...
