---
- platform: template
  fans:
    dyson_fan:
      friendly_name: "Ventilateur"
      value_template: "{{ states('input_boolean.state') }}"
      speed_template: "{{ states('input_select.speed') }}"
      oscillating_template: "{{ states('input_select.osc') }}"
      direction_template: "{{ states('input_select.direction') }}"
      turn_on:
        service: script.dyson_fan_on
      turn_off:
        service: script.dyson_fan_off
      set_oscillating:
        service: !secret rm_mini_send_packet
        data:
          packet:
            - 'JgAkAEoXGRgZLRktGRcZFxgYGRcZGBgZGS0ZLRkYGRcYLRkXGAANBQAAAAA='
      set_direction:
        service: script.turn_on
        data_template:
          entity_id: >
            {% if direction == 'reverse' %}
              script.dyson_fan_cool
            {% elif direction == 'forward %}
              script.dyson_fan_hot
            {% endif %}
...
