---
- platform: broadlink
  mac: !secret rm_mini_mac
  switches:
    - name: TV POWER
      command_on: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='
      command_off: 'JgBYAAABHpISEhMSETYTEhATEhQREhMSEDgRNxISEjcRNxE1EjcSNhM1EhISNhEUERETEhI1EjcSEhE4ExARNxI3ETYTERMSEQAFGAABIEgTAAwpAAEfSRIADQU='
    - name: DYSON POWER
      command_on: 'JgBIAEkYGRgYLhguGRgYGBcYGRcYGhgYGRgYGBgYGBgYGBguGAAMyEgZGBgYLxguFxkYGBcZGBcZGRgZGBgYGRcZGBgYGBgtGAANBQ=='
      command_off: 'JgBIAEkYGRgYLhguGRgYGBcYGRcYGhgYGRgYGBgYGBgYGBguGAAMyEgZGBgYLxguFxkYGBcZGBcZGRgZGBgYGRcZGBgYGBgtGAANBQ=='

- platform: template
  switches:
    tv_lg:
      friendly_name: "TV"
      value_template: "{{ is_state('device_tracker.lg_tv', 'home') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.tv_power
      turn_off:
        service: switch.turn_off
        entity_id: switch.tv_power
    pc:
      friendly_name: "PC"
      value_template: "{{ is_state('device_tracker.pc', 'home') }}"
      turn_on:
        service: shell_command.pc_on
      turn_off:
        service: shell_command.pc_off
...
