---
- platform: broadlink
  host: !secret rm_mini_ip
  mac: !secret rm_mini_mac
  timeout: 15
  type: rm_mini
  switches:
    # Will work on most LG TVs
    tv_lg_power:
      friendly_name: "TV Power"
      command_on: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='
      command_off: 'JgBYAAABHpISEhMSETYTEhATEhQREhMSEDgRNxISEjcRNxE1EjcSNhM1EhISNhEUERETEhI1EjcSEhE4ExARNxI3ETYTERMSEQAFGAABIEgTAAwpAAEfSRIADQU='

- platform: template
  switches:
    tv_lg:
      friendly_name: "TV"
      value_template: "{{ is_state('device_tracker.lg_tv', 'home') }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.tv_lg_power
      turn_off:
        service: switch.turn_off
        entity_id: switch.tv_lg_power
...
